# Generated by Django 3.2 on 2023-04-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255)),
                ('openid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('avatar_url', models.CharField(max_length=255)),
            ],
        ),
    ]
