# Generated by Django 3.2 on 2023-04-11 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_img_path', models.CharField(max_length=255)),
                ('mistake_num', models.IntegerField()),
                ('correct_num', models.IntegerField()),
                ('total_num', models.IntegerField()),
                ('check_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.user')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('your_answer', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('is_mark', models.BooleanField(default=False)),
                ('checklogs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.checklogs')),
            ],
        ),
    ]
