# Generated by Django 3.2 on 2023-04-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_checklogs_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklogs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
